language: android
android:
  components:
    - build-tools-19.1.0
    - android-18
    - sysimg-19
    - extra-android-support
  licenses:
    - android-sdk-license-bcbbd656
    - '.*intel.+'

script:
    - ./gradlew clean test
